# Generated by Django 4.1.5 on 2023-01-24 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
