# Generated by Django 4.1.5 on 2023-01-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_contact_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt_text',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_tags',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
