# Generated by Django 4.1.5 on 2023-01-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_category_alt_text_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_text1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alt_text2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='alt_text3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_tags',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
